version: '3.8'
services:
  crawl2w3c:
    build: .
    volumes:
      - ./crawls:/app/crawls
      - ./src:/app/src
      - ./crawl-config.yaml:/app/crawl-config.yaml
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app/src